"""ajustando PAGAMENTO ID PARA NOT NULL 

Revision ID: 0fd2034313c8
Revises: 7f51c91ed44b
Create Date: 2026-01-13 00:47:33.848177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd2034313c8'
down_revision = '7f51c91ed44b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda_streaming', schema=None) as batch_op:
        batch_op.alter_column('pagamento_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda_streaming', schema=None) as batch_op:
        batch_op.alter_column('pagamento_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
