"""empresa

Revision ID: 46ed2beadd05
Revises: c7a80fc0ff38
Create Date: 2025-12-23 11:24:05.623722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ed2beadd05'
down_revision = 'c7a80fc0ff38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('cliente_telefone_key'), type_='unique')
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])

    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])

    with op.batch_alter_table('licenca_sistema', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])

    with op.batch_alter_table('log_acao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])

    with op.batch_alter_table('permissao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('unique_permissao_usuario'), type_='unique')
        batch_op.create_unique_constraint('unique_permissao_usuario_empresa', ['empresa_id', 'usuario_id', 'categoria', 'acao'])
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])

    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('servico_nome_key'), type_='unique')
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])

    with op.batch_alter_table('tela', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('usuario_nome_key'), type_='unique')
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])

    with op.batch_alter_table('venda_streaming', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda_streaming', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('usuario_nome_key'), ['nome'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('tela', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('servico_nome_key'), ['nome'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('permissao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_permissao_usuario_empresa', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_permissao_usuario'), ['usuario_id', 'categoria', 'acao'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('log_acao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('licenca_sistema', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('cliente_telefone_key'), ['telefone'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('empresa_id')

    op.drop_table('empresa')
    # ### end Alembic commands ###
