"""excluido coluna valor_investido de servico

Revision ID: 54522d105db9
Revises: dc65aaa8491b
Create Date: 2026-01-04 14:28:28.992235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54522d105db9'
down_revision = 'dc65aaa8491b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.drop_column('valor_investido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_investido', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
