"""add campo email em empresa

Revision ID: 7f51c91ed44b
Revises: e782f06fd997
Create Date: 2026-01-13 00:39:37.786923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f51c91ed44b'
down_revision = 'e782f06fd997'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('venda_streaming', schema=None) as batch_op:
        batch_op.alter_column('pagamento_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda_streaming', schema=None) as batch_op:
        batch_op.alter_column('pagamento_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
