"""termos de uso

Revision ID: 871aabbebafb
Revises: 04da687f1d1a
Create Date: 2026-01-23 23:33:55.070266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871aabbebafb'
down_revision = '04da687f1d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('termos_aceitos', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_aceite_termos', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('versao_termos', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ip_aceite', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('ip_aceite')
        batch_op.drop_column('versao_termos')
        batch_op.drop_column('data_aceite_termos')
        batch_op.drop_column('termos_aceitos')

    # ### end Alembic commands ###
