"""empresa null usuario

Revision ID: a15e7e5820c8
Revises: 46ed2beadd05
Create Date: 2025-12-23 13:42:09.071091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15e7e5820c8'
down_revision = '46ed2beadd05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_master', sa.Boolean(), nullable=True))
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_master')

    # ### end Alembic commands ###
