"""nova estrutura stvhd

Revision ID: c7a80fc0ff38
Revises: 
Create Date: 2025-12-23 00:03:52.703620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a80fc0ff38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('licenca_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('dias_acesso', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('imagem', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('telas_total', sa.Integer(), nullable=True),
    sa.Column('valor_investido', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_venda_padrao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comissao_padrao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=120), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('valor_venda_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comissao_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_acao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('usuario_nome', sa.String(length=100), nullable=False),
    sa.Column('acao', sa.String(length=255), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('acao', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'categoria', 'acao', name='unique_permissao_usuario')
    )
    op.create_table('tela',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('vendida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venda_streaming',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('tela_id', sa.Integer(), nullable=True),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('valor_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_comissao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data_venda', sa.DateTime(), nullable=True),
    sa.Column('data_entrega', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.ForeignKeyConstraint(['tela_id'], ['tela.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venda_streaming')
    op.drop_table('tela')
    op.drop_table('permissao')
    op.drop_table('log_acao')
    op.drop_table('conta')
    op.drop_table('usuario')
    op.drop_table('servico')
    op.drop_table('licenca_sistema')
    op.drop_table('cliente')
    # ### end Alembic commands ###
