"""ajustando valor investido

Revision ID: dc65aaa8491b
Revises: 44a14bb4fed7
Create Date: 2026-01-04 13:46:58.236501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc65aaa8491b'
down_revision = '44a14bb4fed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_investido', sa.Numeric(precision=10, scale=4), nullable=True))

    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.alter_column('valor_investido',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.alter_column('valor_investido',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)

    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.drop_column('valor_investido')

    # ### end Alembic commands ###
