"""Add coluna tipo em usuario

Revision ID: e782f06fd997
Revises: ed72b5bf8942
Create Date: 2026-01-13 00:01:11.938961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e782f06fd997'
down_revision = 'ed72b5bf8942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa_pagamento_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('gateway', sa.String(length=30), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.String(length=255), nullable=True),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    op.create_table('venda_token_acesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['venda_id'], ['venda_streaming.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('venda_id')
    )
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_cliente_email'), ['email'], unique=False)

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=80), nullable=True))
        batch_op.create_index(batch_op.f('ix_empresa_slug'), ['slug'], unique=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=100), nullable=True))

    with op.batch_alter_table('venda_streaming', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pix_qr_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pix_qr_code_base64', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('metodo_pagamento', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('pago_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pagamento_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pagamento_status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('email_entrega', sa.String(length=120), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=False)
        batch_op.create_index('ix_venda_empresa_status', ['empresa_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_venda_streaming_pagamento_id'), ['pagamento_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda_streaming', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venda_streaming_pagamento_id'))
        batch_op.drop_index('ix_venda_empresa_status')
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('email_entrega')
        batch_op.drop_column('pagamento_status')
        batch_op.drop_column('pagamento_id')
        batch_op.drop_column('pago_em')
        batch_op.drop_column('valor_pago')
        batch_op.drop_column('metodo_pagamento')
        batch_op.drop_column('pix_qr_code_base64')
        batch_op.drop_column('pix_qr_code')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresa_slug'))
        batch_op.drop_column('slug')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_email'))
        batch_op.drop_column('email')

    op.drop_table('venda_token_acesso')
    op.drop_table('empresa_pagamento_config')
    # ### end Alembic commands ###
